[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
env = ["SEPOLIA_RPC_URL", "ETHERSCAN_API_KEY"]

[etherscan]
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[profile.ci]
fork_url = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
