name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  # this will be set in Settings → Secrets → Actions
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          cd contracts
          forge --version

      - name: Forge fmt
        run: |
          cd contracts
          forge fmt --check

      - name: Forge build
        run: |
          cd contracts
          forge build --sizes

      - name: Forge tests
        run: |
          cd contracts
          forge test -vvv