name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}

jobs:
  test:
    name: Run Forge Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: Show Forge version
        run: |
          cd contracts
          forge --version

      - name: Forge fmt
        run: |
          cd contracts
          forge fmt --check

      - name: Forge build
        run: |
          cd contracts
          forge build --sizes

      - name: Forge tests (unit + integration)
        run: |
          cd contracts
          # If you haven't set `fork_url` in foundry.toml under [profile.ci], you can pass it here:
          forge test -vvv